### ISSUE TITLE
python3 support

### ISSUE THREAD

**Issue by mrtj** [alexcasalboni/ssm-cache-python#1]
Could we have support also for python3? Currently the module fails loading with the error
```
~/anaconda/lib/python3.6/site-packages/ssm_cache/cache.py in __init__(self, param_names, max_age, with_decryption)
     14 
     15     def __init__(self, param_names=None, max_age=None, with_decryption=True):
---> 16         if isinstance(param_names, basestring):
     17             param_names = [param_names]
     18         if not param_names:

NameError: name 'basestring' is not defined
```
as `basestring` was removed in python 3.

**Comment by alexcasalboni** [comment]
Thanks for pointing that out. That is correct, Python3 is currently not supported.

Would you like to collaborate on a PR?

**Comment by mrtj** [comment]
As far as I saw, there are two approaches the folks out there suggest. The first is to rely on some external library, at least `future`:
```python
from past.builtins import basestring    # pip install future
```
The other is to define `basestring` in somewhat hackerly way:
```python
try:
  basestring
except NameError:
  basestring = str
```
I don't know which approach is closer to the philosophy of this library?

**Comment by alexcasalboni** [comment]
If all we need is a workaround for `basestring`, let's fix this quickly. 

But my feeling is that other minor issues will come up with Python3 :) Have you tested it?

**Comment by alexcasalboni** [comment]
Ok, I'm opening a PR in a couple of minutes :)
