### ISSUE TITLE
Cache could convert StringList to Python list

### ISSUE THREAD

**Issue by benkehoe** [alexcasalboni/ssm-cache-python#17]
The StringList type has a defined structure (comma-separated). We could convert this to a Python list of strings when we retrieve a StringList parameter.

**Comment by alexcasalboni** [comment]
+1, I like it!

I'd expect the returned value to be a list automatically, without any configuration or additional method.

Example:

```python
my_param = SSMParameter('my_param_name')
for value in my_param.value:
    print(value)  # print individual values one at a time
```

The same would happen for groups.

Internally, we could implement it without adding new attributes (i.e. just split the string before assigning `self._value`), or by storing the param type internally and making the operation lazy in the `value` property.

The only problem I can see is how to handle local storage. The SSM API will tell us that a returned parameter is a `StringList`, but this wouldn't happen automagically with environment variables or other types of storage.
