### ISSUE TITLE
Dependency issue with botocore in 2.5

### ISSUE THREAD

**Issue by pbassiner** [alexcasalboni/ssm-cache-python#25]
Hi,
even though 2.5 ain't got anything related to `botocore` dependency (apparently), there is a dependency conflict which was working fine in 2.4.

Steps to reproduce:
1. Create Pipfile containing:
```
[[source]]

url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"


[packages]

ssm-cache="==2.5"


[dev-packages]


[requires]

python_version = "3.6"
```
2. Run pipenv install

Output:
```
Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  You can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
  Hint: try $ pipenv lock --pre if it is a pre-release dependency.
Could not find a version that matches botocore<1.11.0,<1.12.0,<2.0.0,==1.10.84,>=1.10.80,>=1.11.1,>=1.3.0
...
There are incompatible versions in the resolved dependencies.
```
(Notice `<1.11.0` vs `>=1.11.1`)

Does this make any sense?

Thanks!

**Comment by alexcasalboni** [comment]
I have tested your Pipfile and everything seems to work (clean env, upgrade to 2.5, and downgrade to 2.4).

Could you please share which versions of `boto3` and `botocore` are currently installed in your env?

**Comment by pbassiner** [comment]
Hi @alexcasalboni,
thanks for the quick reply. Funny thing is, after locking with `--pre` in the project I had issues with (which solved it), I've created a new Pipfile in a clean env and performed the steps exactly as I described before and now it works.
If I'm ever able to reproduce this again I'll reopen the issue.

Thanks again!

**Comment by alexcasalboni** [comment]
No worries, I'm glad you managed to solve the issue 😄 

And thanks for using `ssm-cache`!
