### ISSUE TITLE
No 2.7 tag or GitHub release, but it does exist in PyPI

### ISSUE THREAD

**Issue by pawelad** [alexcasalboni/ssm-cache-python#31]
Hi!

I was just browsing through your project (which looks awesome BTW!) and noticed that the latest git tag / GitHub release is 2.6 but there is a 2.7 released on PyPI - I'm guessing you just forgot to do the former, but wanted to mention it / make sure, as I was baffled for a couple minutes there.

**Comment by alexcasalboni** [comment]
Thanks for the heads-up 🙏 

I've just pushed it!
