### ISSUE TITLE
Return 'SSMParameterGroup' parameters as dict

### ISSUE THREAD

**Issue by pawelad** [alexcasalboni/ssm-cache-python#33]
Hi!

This is a feature request (that I would be happy to implement).

I think it would be worth it to be able to return `group.parameters("/path")` as a dictionary with key being the path (either absolute or local to group path) and value being the, well, value : )

Let me know what you think!

**Comment by pawelad** [comment]
To illustrate what I meant:

```python
def get_ssm_parameters(path):
    """
    Helper method to get all nested AWS SSM parameters.

    :param path: parameters path
    :type path: str
    :returns: all nested parameters
    :rtype: dict
    """
    group = SSMParameterGroup()
    params = group.parameters(path)

    return {
        param.name: param.value
        for param in params
    }
```

```python
In[3]: get_ssm_parameters("/database/foo/production")
Out[3]: 
{'/database/foo/production/password': 'foobar',
 '/database/foo/production/user': 'foo'}
```

It could be an extra argument to `group.parameters`, something like `as_dict` (so `params = group.parameters(path, as_dict=True)`) but I'd also understand if this is so simple to implement on client side that it doesn't make sense to include in the source.

**Comment by alexcasalboni** [comment]
Hi @pawelad this could be achieved with a simple one-liner and a dict comprehension :)

```python

group = SSMParameterGroup()
params = group.parameters(base_path)

#absolute path
params_dict = {param.name: param.value for param in params}

#relative path
params_dict_rel = {param.name.lstrip(base_path): param.value for param in params} 
```

I'm not 100% sure this deserves its own built-in implementation. It could be something like `group.to_json()` or something similar that creates a dict representation of all the parameters, but I wouldn't overcomplicate `group.parameters` for this.

**Comment by pawelad** [comment]
Yeah, I'm perfectly fine with that answer - the only reason I mentioned it is because I _assumed_ it will look like, was surprised when it didn't, and then started thinking about whether other users would expect that as well. But since nobody else opened an issue before, my use case might not be as standard as I thought after all ; -)
