### ISSUE TITLE
Allow passing custom 'boto3' arguments to 'Refreshable' class

### ISSUE THREAD

**Issue by pawelad** [alexcasalboni/ssm-cache-python#34]
Hi!

It would be nice to be able to pass extra `boto3` related arguments like `aws_region` to the objects inheriting from `Refreshable`.

I could try and implement it if you like the idea.

**Comment by alexcasalboni** [comment]
Hi @pawelad, you could achieve this by passing your custom ssm client.

Something like this:

```python
import boto3
my_client = boto3.client('ssm', ...)
SSMParameter.set_ssm_client(client)
```

Is there anything specific that you wouldn't be able to achieve with the approach above?

**Comment by pawelad** [comment]
Oh, my bad - I looked exactly at that function but for some reason thought (assumed?) that for it to work you have to create your own class that inherits from `Refreshable` and _implements_ that method. This makes way more sense : -)
