### ISSUE TITLE
Remove boto3 dependency or make it optional?

### ISSUE THREAD

**Issue by alexcasalboni** [alexcasalboni/ssm-cache-python#4]
The boto3 SSM client could be provided at initialization time. 

This way, we could remove the `boto3` dependency at all (and avoid version conflicts).
Additionally, eventual SDK configurations wouldn't be lost (e.g. AWS profile, access keys, etc.), although the best practice is to configure them at the environment level.

**Comment by benkehoe** [comment]
You want this at the class level, because client set up is relatively time consuming

**Comment by glb** [comment]
@benkehoe is your suggestion in #3 a potential implementation of a solution for this?

**Comment by benkehoe** [comment]
Yep!

**Comment by glb** [comment]
_Yoink!_ (pending resolution of iRobotCorporation/cfn-custom-resource#6)
