### ISSUE TITLE
'tests' package installed to 'site-packages'?

### ISSUE THREAD

**Issue by johnmee** [alexcasalboni/ssm-cache-python#43]
I've been having some trouble with my application which has a "tests" module in the root directory.

Pytest seems to encounter a "tests" module which is installed to 'site-packages' and uses that in preference to the one in my application.  This problem appears and disappears according to whether this package is installed, or not.

Does this package place a module named 'tests' into 'sites-packages'?

(And if so, can we please not do that).

**Comment by alexcasalboni** [comment]
Hi @johnmee, thanks for reporting this!

I've just merged #44 and published `ssm-cache==2.10`. 

Please reopen this issue if it happens again.

**Comment by johnmee** [comment]
Wow. That was quick.  Had I known it to be that easy I would've sent a PR.
Thanks Alex.
